#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Pod::Usage;
use Acme::Text::Inao;

my $file = shift;
pod2usage(1) unless $file;

my $html = Acme::Text::Inao->new->from_inao(do {
    open my $fh, '<:utf8', $file or die "$!: $file";
    local $/;
    <$fh>;
})->to_html;

binmode STDOUT, ':utf8';
print $html;

__END__

=head1 NAME

inao2html - inao format text を HTML に変換します

=head1 SYNOPSIS

$ inao2html genko.txt

=cut
