#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Pod::Usage;
use Acme::Text::Inao;

my $file = shift;
pod2usage(1) unless $file;

my $stat = Acme::Text::Inao->new->from_inao(do {
    open my $fh, '<:utf8', $file or die "$!: $file";
    local $/;
    <$fh>;
})->to_status;

print "原稿の集計\n
本文の文字数            : $stat->{body_length}
行数                    : $stat->{lines}
書いたページ数          : $stat->{raw_pages}
タイトル部含めたページ数: $stat->{pages}
";

__END__

=head1 NAME

inaostat - inao format text の分量を計算します

=head1 SYNOPSIS

$ inaostat genko.txt

=cut
